services:
  # Mock Windows Environment (PowerShell Core on Linux)
  windows-mock:
    build:
      context: .
      dockerfile: tests/docker/Dockerfile.windows-mock
    container_name: wmr-windows-mock
    volumes:
      - ./:/workspace
      - mock-cloud-storage:/mock-cloud
      - ./tests/mock-data/registry:/mock-registry
      - ./tests/mock-data/appdata:/mock-appdata
      - ./tests/mock-data/programfiles:/mock-programfiles
    environment:
      - MOCK_MODE=true
      - CLOUD_PROVIDER=mock
      - CLOUD_PATH=/mock-cloud
      - BACKUP_ROOT=/workspace/test-backups
      - MACHINE_NAME=TEST-MACHINE
      - USER_PROFILE=/mock-appdata/Users/TestUser
      - PROGRAM_FILES=/mock-programfiles
      - REGISTRY_ROOT=/mock-registry
    networks:
      - wmr-test-network
    depends_on:
      - mock-cloud-server
      - wsl-mock

  # Mock WSL Environment (Ubuntu)
  wsl-mock:
    build:
      context: .
      dockerfile: tests/docker/Dockerfile.wsl-mock
    container_name: wmr-wsl-mock
    volumes:
      - ./:/workspace
      # Mount mock data to dedicated test paths instead of overriding system directories
      - ./tests/mock-data/wsl/home:/mnt/test-data/home
      - ./tests/mock-data/wsl/config:/mnt/test-data/config
      - ./tests/mock-data/wsl/dotfiles:/mnt/test-data/dotfiles
    environment:
      - WSL_DISTRO_NAME=Ubuntu-22.04
      - WSL_VERSION=2
      - USER=testuser
      - HOME=/home/testuser
      - MOCK_TEST_DATA_HOME=/mnt/test-data/home
      - MOCK_TEST_DATA_CONFIG=/mnt/test-data/config
      - MOCK_TEST_DATA_DOTFILES=/mnt/test-data/dotfiles
    networks:
      - wmr-test-network
    command: /bin/bash -c "tail -f /dev/null"

  # Mock Cloud Storage Server (simulates OneDrive/Google Drive/Dropbox)
  mock-cloud-server:
    build:
      context: .
      dockerfile: tests/docker/Dockerfile.cloud-mock
    container_name: wmr-cloud-mock
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - mock-cloud-storage:/cloud-storage
      - ./tests/mock-data:/mock-data
    environment:
      - CLOUD_TYPE=multi
      - ONEDRIVE_PATH=/cloud-storage/OneDrive
      - GOOGLEDRIVE_PATH=/cloud-storage/GoogleDrive
      - DROPBOX_PATH=/cloud-storage/Dropbox
    networks:
      - wmr-test-network

  # Test Runner (PowerShell with Pester)
  test-runner:
    build:
      context: .
      dockerfile: tests/docker/Dockerfile.test-runner
    container_name: wmr-test-runner
    volumes:
      - ./:/workspace
      - mock-cloud-storage:/mock-cloud
      - ./test-results:/test-results
      - ./tests/mock-data/registry:/mock-registry
      - ./tests/mock-data/appdata:/mock-appdata
      - ./tests/mock-data/programfiles:/mock-programfiles
      - ./tests/mock-data/steam:/mock-steam
      - ./tests/mock-data/epic:/mock-epic
      - ./tests/mock-data/gog:/mock-gog
      - ./tests/mock-data/ea:/mock-ea
      # Mount Docker socket to allow test-runner to communicate with other containers
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PESTER_OUTPUT_PATH=/test-results
      - MOCK_WINDOWS_HOST=wmr-windows-mock
      - MOCK_WSL_HOST=wmr-wsl-mock
      - MOCK_CLOUD_HOST=wmr-cloud-mock
    networks:
      - wmr-test-network
    depends_on:
      - windows-mock
      - wsl-mock
      - mock-cloud-server
    command: /bin/bash -c "tail -f /dev/null"

  # Gaming Platform Mocks
  gaming-mock:
    build:
      context: .
      dockerfile: tests/docker/Dockerfile.gaming-mock
    container_name: wmr-gaming-mock
    volumes:
      - mock-steam:/mock-steam
      - mock-epic:/mock-epic
      - mock-gog:/mock-gog
      - mock-ea:/mock-ea
    environment:
      - STEAM_PATH=/mock-steam
      - EPIC_PATH=/mock-epic
      - GOG_PATH=/mock-gog
      - EA_PATH=/mock-ea
    networks:
      - wmr-test-network

  # Package Manager Mocks
  package-mock:
    build:
      context: .
      dockerfile: tests/docker/Dockerfile.package-mock
    container_name: wmr-package-mock
    volumes:
      - mock-chocolatey:/mock-chocolatey
      - mock-scoop:/mock-scoop
      - mock-winget:/mock-winget
    environment:
      - CHOCOLATEY_PATH=/mock-chocolatey
      - SCOOP_PATH=/mock-scoop
      - WINGET_PATH=/mock-winget
    networks:
      - wmr-test-network

volumes:
  mock-cloud-storage:
  mock-steam:
  mock-epic:
  mock-gog:
  mock-ea:
  mock-chocolatey:
  mock-scoop:
  mock-winget:

networks:
  wmr-test-network:
    driver: bridge 